# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chst' do
  use_frameworks!

  #Firebase
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod "Firebase/Database"
  
  #Facebook 
  pod "FBSDKLoginKit"

  #Google
  pod 'GoogleSignIn', '~> 5.0'
  
  pod 'MessageKit'
  pod 'RealmSwift'
  pod 'JGProgressHUD'
  pod 'SDWebImage'
  
end
